id: P798A42C8
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00KG09978
  instance_id: http://purl.bdrc.io/resource/IE00KG09978
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - མཁན་ཆེན་ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པའི་རྟོགས་བརྗོད་དང་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  alt_title:
    en-x-mixed:
    - Mi-ñag mkhan chen Thub-bstan-chos-kyi-grags-paʼi rtogs brjod daṅ gsuṅ rtsom
      phyogs bsgrigs /[Bsod-nams-ñi-mas brtsams ; gtso sgrig pa, Padma-theg-mchog-blo-ldan].
    zh-latn-pinyin-x-ndia:
    - kan bu qu zha zhuan lue yu zuo pin ji
  author: http://purl.bdrc.io/resource/P00KG09979
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    da233da76f924fc194c1cb42993898b8:
      title: པོད ༡་མཁན་ཆེན་ཐུབ་བསྟན་ཆོས་ཀྱི་གྲགས་པའི་རྟོགས་བརྗོད་དང་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས
      volume_number: 1
      base_file: UT00KG09978_I00KG010138_0000.txt
      reference: http://purl.bdrc.io/resource/VLBF5302312106AA45
      image_group: I00KG010138
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW00KG09978
  - http://purl.bdrc.io/resource/W00KG09978
  ocr_software: Namsel
created_at: '2021-12-22T10:21:42.553289'
last_modified_at: '2021-12-22T10:21:42.553296'
statistics:
  total_words: 88612
  total_non_words: 10212
quality:
  non_words_ratio: 0.12
